### ISSUE TITLE
Fix Profile

### ISSUE THREAD

**Issue by fthbintang** [fthbintang/kedai-kopi#12]
Seluruh Form di Halaman Profile Tidak bisa di Update.

**Comment by fthbintang** [comment]
Mas ari, bisa minta tolong agar foto profile bisa di upload.

**Comment by Nikko146** [comment]
Iya mas, nanti kita diskusi di discord aja ya. Jam 9 malam nanti.

**Comment by fthbintang** [comment]
Fixed!

**Comment by fthbintang** [comment]
Fixed
